
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      # run build
      - run: npm run build

      # run tests!
      - run:
          name: Unit Tests
          command: ./node_modules/.bin/jest -w 2 --coverage

      # upload coverage
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash)

  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependency
          command: npm install
      # run tests!
      - run:
          name: Execute unit tests
          command: ./node_modules/.bin/jest -w 2 --coverage
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Build packages
          command: npm run build
      - run:
          name: Publish package - main
          command: npm publish --access public
      - run:
          name: Publish package - umd
          working_directory: ~/repo/dist/umd
          command: npm publish --access public
      - run:
          name: Publish package - node
          working_directory: ~/repo/dist/node
          command: npm publish --access public
      - run:
          name: Publish package - es5
          working_directory: ~/repo/dist/es5
          command: npm publish --access public
      - run:
          name: Publish package - es6
          working_directory: ~/repo/dist/es6
          command: npm publish --access public

workflows:
  version: 2
  main:
    jobs:
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: /.*/


