
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      # run build
      - run: npm run build

      # run tests!
      - run: ./node_modules/.bin/jest -w 1 --coverage

      # upload coverage
      - run: bash <(curl -s https://codecov.io/bash)


  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package
          command: npm publish --access public

workflows:
  version: 2
  main:
    jobs:

      - build

      - deploy-approval:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          type: approval
          requires:
            - build

      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - deploy-approval

