name: Deno CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: setup Deno
      uses: denolib/setup-deno@v2
    - name: install nodejs deps
      run: npm ci
    - name: build for deno
      run: npm run build:deno
    - name: run deno test
      run: deno test ./dist/deno/test/
