name: Deno CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'
  # daily check at 02:00 AM UTC
  schedule:
    - cron: '0 2 * * *'

jobs:

  build-test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: setup deno
      uses: denolib/setup-deno@v2

    - name: install nodejs deps
      run: npm ci

    - name: build source for deno
      run: npm run build:deno

    - name: build test cases for deno
      run: npm run build:deno:test

    - name: run deno test
      run: deno test --reload ./dist/deno/test/
